export enum API_BASE_URL {
    BINANCE = 'http://localhost:3001/binance',
    BITFINEX = 'http://localhost:3001/bitfinex',
    HUOBI = 'http://localhost:3001/huobi',
    KRAKEN = 'http://localhost:3001/kraken',
}

export enum QUERY {
    BINANCE_GET_TICKER = 'BINANCE_GET_TICKER',
    BINANCE_GET_HISTORY = 'BINANCE_GET_HISTORY',
    BITFINEX_GET_TICKER = 'BITFINEX_GET_TICKER',
    BITFINEX_GET_HISTORY = 'BITFINEX_GET_HISTORY',
    HUOBI_GET_TICKER = 'HUOBI_GET_TICKER',
    HUOBI_GET_HISTORY = 'HUOBI_GET_HISTORY',
    KRAKEN_GET_TICKER = 'KRAKEN_GET_TICKER',
    KRAKEN_GET_HISTORY = 'KRAKEN_GET_HISTORY',
}